name: PV-Star
author: JCThePants
main: PVStar
version: 0.0-beta
depend: [NucleusFramework]
commands:
    pv:
        description: Base command for PV-Star
        usage: |
            ERROR!
    pvs:
        description: Base command for PV-Star
        usage: |
            ERROR!
    pvp:
        description: Base command for PV-Star
        usage: |
            ERROR!
    pve:
        description: Base command for PV-Star
        usage: |
            ERROR!
    pvstar:
        description: Base command for PV-Star
        usage: |
            ERROR!